import { Router } from 'express';
import { authRouter } from './auth';
import { dietFormRouter } from './dietForm';
import { paymentRouter } from './payment';
import { awsKeysRouter } from './awsKeys';
import { dietitianRouter } from './dietitian';
import { dietitiansRouter } from './dietitians';
import { adminRouter } from './admin';
import { dietPlanRouter } from './dietPlan';
import { settingsRouter } from './settings';
import { contactRouter } from './contact';
import { appointmentRouter } from './appointment';
import { webhookRouter } from './webhook';
import { walletRouter } from './wallet';
import { banksRouter } from './banks';
import { followUpsRouter } from './followUps';
import { userRouter } from './user';
import { couponRouter } from './coupon';
import { courseRouter } from './course';

export const router = Router();

router.use('/auth', authRouter);
router.use('/diet-form', dietFormRouter);
router.use('/payment', paymentRouter);
router.use('/aws-keys', awsKeysRouter);
router.use('/dietitian', dietitianRouter);
router.use('/dietitians', dietitiansRouter);
router.use('/admin', adminRouter);
router.use('/diet-plan', dietPlanRouter);
router.use('/wallet', walletRouter);
router.use('/contact', contactRouter);
router.use('/appointments', appointmentRouter);
router.use('/webhooks', webhookRouter);
router.use('/banks', banksRouter);
router.use('/follow-ups', followUpsRouter);
router.use('/user', userRouter);
router.use('/coupons', couponRouter);
router.use('/course', courseRouter);
router.use('/', settingsRouter);
